- name: installing set of tools via apt
  become: true
  apt:
    name: virtualbox
    state: present
    update_cache: true

- name: get binaries
  get_url: url="{{ item.url }}" dest="{{ item.dest }}"
  with_items:
    - url: "https://github.com/kubernetes/minikube/releases/download/v1.9.2/minikube-linux-amd64"
      dest: "/opt/minikube"
    - url: "https://storage.googleapis.com/kubernetes-release/release/v1.16.8/bin/linux/amd64/kubectl"
      dest: "/opt/kubectl"

- name: chmod binaries
  file: dest="/opt/{{ item }}" mode=0755
  with_items:
    - minikube
    - kubectl
